### PR TITLE
updated swig binding with mapper_libersion()->mapper_version() change

### PR DESCRIPTION
**Pull request by johnty**

### CODE REVIEW

**Comment by johnty** [comment]
actually i accidentally checked in the tkgui.py example - that probably shouldn't be changed (although we do need a way to handle it when the port is "None")

**Comment by malloch** [comment]
Sorry – I had already fixed this but hadn’t pushed the commit to github!

Joe

**Comment by malloch** [comment]
I fixed a bug in the Python bindings that was causing the device ‘port’ property to always return Py_None. This should fix the problem you encountered in the tkgui.py example.

thanks,
Joe

**Comment by johnty** [comment]
great. thanks!

**Pull request closed without merging**
